import DMC_COLORS from "./dmcColors";
import PERLER_COLORS from "./palettes/perlerColors";
import YARN_COLORS from "./palettes/yarnColors";
import MOSAIC_COLORS from "./palettes/mosaicColors";

// All grid-based craft types share the same conversion engine.
// Special types (svg, paintByNumbers, coloringPage) use dedicated generators.

const CRAFT_TYPES = {
  crossStitch: {
    id: "crossStitch",
    name: "Cross-Stitch",
    desc: "DMC thread pattern with symbols grid",
    palette: DMC_COLORS,
    brandLabel: "DMC",
    unitLabel: "stitches",
    defaults: { gridWidth: 60, maxColors: 20 },
    widthRange: [20, 200],
    colorRange: [4, 60],
    pdfSubtitle: "Cross-Stitch Pattern",
    zipName: "cross-stitch-patterns",
  },
  diamondPainting: {
    id: "diamondPainting",
    name: "Diamond Painting",
    desc: "DMC drill color grid for diamond art",
    palette: DMC_COLORS,
    brandLabel: "DMC Drill",
    unitLabel: "drills",
    defaults: { gridWidth: 50, maxColors: 25 },
    widthRange: [20, 150],
    colorRange: [4, 50],
    pdfSubtitle: "Diamond Painting Pattern",
    zipName: "diamond-painting-patterns",
  },
  perlerBeads: {
    id: "perlerBeads",
    name: "Perler Beads",
    desc: "Fuse bead pattern with pegboard layout",
    palette: PERLER_COLORS,
    brandLabel: "Perler",
    unitLabel: "beads",
    defaults: { gridWidth: 29, maxColors: 15 },
    widthRange: [14, 87],
    colorRange: [3, 40],
    pdfSubtitle: "Perler Bead Pattern",
    zipName: "perler-bead-patterns",
    pegboardNote: "Standard pegboard: 29x29 beads",
  },
  c2cCrochet: {
    id: "c2cCrochet",
    name: "C2C Crochet",
    desc: "Corner-to-corner graph with written instructions",
    palette: YARN_COLORS,
    brandLabel: "Yarn",
    unitLabel: "squares",
    defaults: { gridWidth: 40, maxColors: 8 },
    widthRange: [15, 100],
    colorRange: [2, 20],
    pdfSubtitle: "C2C Crochet Graph",
    zipName: "c2c-crochet-patterns",
    hasWrittenInstructions: true,
  },
  knitting: {
    id: "knitting",
    name: "Knitting Chart",
    desc: "Colorwork chart for knitting",
    palette: YARN_COLORS,
    brandLabel: "Yarn",
    unitLabel: "stitches",
    defaults: { gridWidth: 40, maxColors: 6 },
    widthRange: [10, 120],
    colorRange: [2, 12],
    pdfSubtitle: "Knitting Colorwork Chart",
    zipName: "knitting-patterns",
  },
  pixelArt: {
    id: "pixelArt",
    name: "Pixel Art",
    desc: "Retro pixel grid with RGB palette",
    palette: null, // uses raw quantized RGB
    brandLabel: "Color",
    unitLabel: "pixels",
    defaults: { gridWidth: 32, maxColors: 16 },
    widthRange: [8, 128],
    colorRange: [2, 32],
    pdfSubtitle: "Pixel Art Pattern",
    zipName: "pixel-art-patterns",
    useRawRGB: true,
  },
  punchNeedle: {
    id: "punchNeedle",
    name: "Punch Needle",
    desc: "Low-res pattern for punch needle / rug tufting",
    palette: YARN_COLORS,
    brandLabel: "Yarn",
    unitLabel: "loops",
    defaults: { gridWidth: 30, maxColors: 10 },
    widthRange: [10, 60],
    colorRange: [2, 15],
    pdfSubtitle: "Punch Needle Pattern",
    zipName: "punch-needle-patterns",
  },
  mosaic: {
    id: "mosaic",
    name: "Mosaic Tiles",
    desc: "Tile layout with ceramic color codes",
    palette: MOSAIC_COLORS,
    brandLabel: "Tile",
    unitLabel: "tiles",
    defaults: { gridWidth: 30, maxColors: 12 },
    widthRange: [10, 80],
    colorRange: [2, 24],
    pdfSubtitle: "Mosaic Tile Pattern",
    zipName: "mosaic-patterns",
  },
  paintByNumbers: {
    id: "paintByNumbers",
    name: "Paint by Numbers",
    desc: "Numbered region template for painting",
    palette: null,
    brandLabel: "Color",
    unitLabel: "regions",
    defaults: { gridWidth: 80, maxColors: 15 },
    widthRange: [40, 200],
    colorRange: [4, 30],
    pdfSubtitle: "Paint by Numbers Template",
    zipName: "paint-by-numbers",
    isSpecial: true,
  },
  coloringPage: {
    id: "coloringPage",
    name: "Coloring Page",
    desc: "Line art outline for coloring",
    palette: null,
    brandLabel: null,
    unitLabel: null,
    defaults: { gridWidth: 100, maxColors: 1 },
    widthRange: [60, 300],
    colorRange: null,
    pdfSubtitle: "Coloring Page",
    zipName: "coloring-pages",
    isSpecial: true,
    noColorControl: true,
  },
  svgCut: {
    id: "svgCut",
    name: "SVG Cut File",
    desc: "Vector traced outline for Cricut / Silhouette",
    palette: null,
    brandLabel: null,
    unitLabel: null,
    defaults: { gridWidth: 100, maxColors: 1 },
    widthRange: [60, 300],
    colorRange: null,
    pdfSubtitle: "SVG Cut File",
    zipName: "svg-cut-files",
    isSpecial: true,
    noColorControl: true,
    outputFormat: "svg",
  },
};

export const CRAFT_LIST = Object.values(CRAFT_TYPES);
export default CRAFT_TYPES;
